# Generated by Django 4.0 on 2021-12-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='coffeeapi.Ingredient'),
        ),
    ]
