# Generated by Django 4.0 on 2021-12-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapi', '0002_alter_coffee_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
